name: Build and Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'  # Enable automatic npm cache based on package-lock.json

      - name: Install dependencies
        run: npm ci  # Uses package-lock.json for clean, deterministic install

      - name: Type check
        run: npm run tsc --noEmit

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
        env:
          VITE_DEV_SERVER_URL: ${{ secrets.VITE_DEV_SERVER_URL }}
          VITE_DJANGO_BASE_URL: ${{ secrets.VITE_DJANGO_BASE_URL }}
          VITE_DJANGO_CONFIG_GET_THRESH: ${{ secrets.VITE_DJANGO_CONFIG_GET_THRESH }}
          VITE_DJANGO_CONFIG_SET_THRESH: ${{ secrets.VITE_DJANGO_CONFIG_SET_THRESH }}
          VITE_SUPABASE_KEY: ${{ secrets.VITE_SUPABASE_KEY }}
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
